### ISSUE TITLE
Does 1.1.1 support all object types? Only Function supported?

### ISSUE THREAD

**Issue by reggi** [okunishinishi/node-argx#3]
``` javascript
function argxGetNumberType(fn, string, number){
  var args = argx(arguments)
  var a = {}
  a.fn = args.shift(Function) // works
  a.str = args.shift(String) // undefined
  a.numb = args.shift(Number) // undefined
  console.log(a)
}

argxGetNumberType(argxGetNumberType, "hello", 3)
```

**Comment by okunishinishi** [comment]
@reggi 

Now fixed in [v1.1.4](https://github.com/okunishinishi/node-argx/commit/dfcb7885874434a52a5fd3e9fbaaf09031f2b3d7)

FYI, the reason why only function worked is that the `instanceof` operator hits `Function` but not other buildin types.
I used `instanceof` and `isPrototypeOf` for comparison inside `argx` and,

``` javascript
(function a(){}) instanceof Function // true
Function.isPrototypeOf(function a(){}) // false
"f" instanceof String // false
String.isPrototypeOf("f") // false
1 instanceof Number // false
Number.isPrototypeOf(1) // false
```

So, I added direct comparison like `if (type ==== String) {}`,
it works fine with `String` and `Number`, and `Array` now.
